### ISSUE TITLE
IMAGENES WIKI

### ISSUE THREAD

**Issue by margarcac1** [egc-sierrezuela-3/decide#87]
![imagen](https://user-images.githubusercontent.com/73033204/148677937-f733127e-69fc-44f3-81e6-d3c45c2f63ed.png)

**Comment by margarcac1** [comment]
![imagen](https://user-images.githubusercontent.com/73033204/148678049-9f44f3ee-984c-4e19-b4e6-79a2a7b7fe3f.png)

**Comment by margarcac1** [comment]
![imagen](https://user-images.githubusercontent.com/73033204/148678097-886c0406-f3a4-4224-996d-38dcfe73011c.png)

**Comment by margarcac1** [comment]
![imagen](https://user-images.githubusercontent.com/73033204/148678136-bc85e486-9615-4c15-8dbb-aca03cef79d9.png)

**Comment by margarcac1** [comment]
![imagen](https://user-images.githubusercontent.com/73033204/148678163-5d76af05-ed9f-4062-bc9f-6f48fcc61859.png)

**Comment by margarcac1** [comment]
![imagen](https://user-images.githubusercontent.com/73033204/148678467-16190f7a-8592-438f-982a-971db23b8691.png)

**Comment by jesrolcad** [comment]
![image](https://user-images.githubusercontent.com/72762597/148803409-92a08a89-34f6-4f71-a8c0-2f981930ecbd.png)
